# SwiftLint Configuration for Utterance
# Based on Alamofire's configuration

excluded:
  - .build
  - .swiftpm
  - Tests

disabled_rules:
  - trailing_comma
  - nesting
  - function_parameter_count

opt_in_rules:
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@discardableResult"
    - "@available"
    - "@MainActor"
    - "@Sendable"

line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - to
    - UT

type_name:
  min_length: 2
  max_length: 50
